version: "2.4"
services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - 5432
    tty: true
    environment:
      POSTGRES_DB: sampledb
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: topsecret

  api:
    image: acme/api-debug:1.0
    build:
      context: api
      dockerfile: Dockerfile-debug
    ports:
      - 5000:5000
    tty: true

volumes:
  pg-data: