FROM mcr.microsoft.com/dotnet/core/sdk:3.1
#WORKDIR /app
#COPY api/api.csproj ./
#RUN dotnet restore
#COPY api api
#EXPOSE 5000-5001
#CMD dotnet watch run --no-restore --urls

# install the .net core debugger
RUN apt-get update
RUN apt-get -y --no-install-recommends install unzip
RUN apt-get -y --no-install-recommends install procps
RUN rm -rf /var/lib/apt/lists/*

RUN curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

WORKDIR /app

CMD dotnet watch run --urls http://0.0.0.0:5000 -r linux-x64